# example from https://github.com/aormsby/Fork-Sync-With-Upstream-action
name: auto-update
on:
  schedule:
    - cron:  '13 2 * * *'

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream latest
    steps:
    - name: Checkout release
      uses: actions/checkout@v2
      with:
        ref: dunfell
        submodules: 'recursive'
    - name: Pull (Fast-Forward) upstream changes
      id: sync
      uses: reMarkable/Fork-Sync-With-Upstream-action@nikolai/other_git_providers
      with:
        upstream_repository: schnitzeltony/meta-qt5-extra
        upstream_provider: github
        upstream_branch: dunfell
        target_branch: dunfell
        git_pull_args: '--allow-unrelated-histories'                   # optional arg use, defaults to simple 'pull'
        github_token: ${{ secrets.GITHUB_TOKEN }}   # optional, for accessing repos that require authentication
    - name: Check for new commits
      if: steps.sync.outputs.has_new_commits
      run: echo "There were new commits."
    - name: Timestamp
      run: date

